# Basic Python

## 1. Split this string

In [ ]:
str1 = "Hi there Sam!"

In [ ]:
a=str1.split()
a

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 123456742

In [ ]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 123456742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'e':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'super']}]}]}

In [ ]:
print(d['e'][3]["tricky"][3]['target'][3])

super


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
#4.1
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#4.2
arr1=np.ones(10)*5
print(arr1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
even=np.arange(20,35,2)
print("Array of even integers from 25 35")
print(even)

Array of even integers from 25 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x=np.arange(0,9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [38]:
import pandas as pd
import numpy as np

In [40]:
data=np.arange(50,101,10).reshape(3,2)
df = pd.DataFrame(data,columns=["Maths","Scienece"])
print(df)

   Maths  Scienece
0     50        60
1     70        80
2     90       100


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [35]:
pd.date_range("1-2-2023","10-2-2023")

DatetimeIndex(['2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
               '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09',
               '2023-01-10', '2023-01-11',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=274, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [36]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [37]:
m= pd.DataFrame(lists, columns =['s.no','letter','numbers'])
print(m)

   s.no letter  numbers
0     1    aaa       22
1     2    bbb       25
2     3    ccc       24
